<?php

include_once('incourage_pdfbulletin.features.inc');

/**
 * Implements hook_voipscript_load_script().
 */
function incourage_pdfbulletin_voipscript_load_script($script_name, $params = NULL) {
  if ($script_name == 'incourage_upcoming') {
    module_load_include('inc', 'incourage_pdfbulletin', 'incourage_pdfbulletin.script');
    return _incourage_upcoming_script();
  }
}

/**
 * Implements hook_voipscript_get_script_names().
 */
function incourage_pdfbulletin_voipscript_get_script_names() {
  return array(
    'incourage_upcoming',
  );
}

/**
 * Implements hook_form_type_id_alter().
 *
 * Change exposed views date filter to US date format.
 */
function incourage_pdfbulletin_form_views_exposed_form_alter(&$form, $form_state) {
  if (isset($form['date_filter']['value']['#date_format'])) {
    $form['date_filter']['value']['#date_format'] = 'm-d-Y';
  }
}
