<?php

include_once('incourage_voipdrupal.features.inc');

function incourage_voipdrupal_voipscript_load_script($script_name, $params = NULL) {
  if ($script_name == 'incourage_extensions') {
    module_load_include('inc', 'incourage_voipdrupal', 'incourage_voipdrupal.script');
    return _incourage_voipdrupal_welcome();
  }
  if ($script_name == 'incourage_play_extension') {
    // silent version of get_play_extension.
    module_load_include('inc', 'incourage_voipdrupal', 'incourage_voipdrupal.script');
    return _incourage_voipdrupal_play_extension_script($params['eid'], $params);
  }
}

/**
 * Implementation of hook_voipscript_get_script_names().
 */
function incourage_voipdrupal_voipscript_get_script_names() {
  return array(
    'incourage_extensions',
    'incourage_play_extension',
  );
} 
