<?php

include_once('incourage_directory.features.inc');

/**
 * Implementation of hook_voipscript_load_script().
 */
function incourage_directory_voipscript_load_script($script_name, $params = NULL) {
  if ($script_name == 'incourage_location') {
    module_load_include('inc', 'incourage_directory', 'incourage_directory.script');
    $node = node_load($params['nid']);
    return _incourage_directory_location_script($node);
  }
}

/**
 * Implementation of hook_voipscript_get_script_names().
 */
function incourage_directory_voipscript_get_script_names() {
  return array(
    'incourage_location',
  );
}

/**
 * Implements hook_block().
 */
function incourage_directory_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      return array(
        'anon-post' => array(
          'info' => t('Anonymous user posting note'),
          'cache' => BLOCK_NO_CACHE, // far to simple
        ),
      );
    case 'view':
      // how much hard coded path info for one block:-
      if ($delta == 'anon-post' && arg(0) == 'node' && arg(1) == 'add' && (arg(2) == 'event' || arg(2) == 'location')) {
        global $user;
        if ($user->uid == 0) {
          $block = array(
            'subject' => '',
            'content' => t('Please <a href="/user/register">sign up</a> to What\'s Up before submitting a new %type. That will make it possible for you to edit or delete that event at a later time and receive notifications from the system.', array('%type' => arg(2))),
          );
        }
        if (isset($block)) {
          return $block;
        }
        else {
          return array('subject' => '', 'content' => '');
        }
      }
  }
}

/**
 * Implements hook_form_FORMID_alter().
 */
function incourage_directory_form_location_node_form_alter(&$form, &$form_state) {
  $form['title']['#description'] = t('The name people usually use to refer to this location.');
  $form['body_field']['body']['#rows'] = 5;
}
